name = "plata"
account_id = "79fef09180b6e0758d7f7aa45cc3e9ec" # Find this in your Cloudflare dashboard
main = "./.cloudflare/worker.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]
[site]
bucket = "./.cloudflare/public"

[build]
command = "npm run build"

[vars]
# Public variables
PUBLIC_SUPABASE_URL = "https://uvaiigoyxbxcgetqdodl.supabase.co"
PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2YWlpZ295eGJ4Y2dldHFkb2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MzQwMDYsImV4cCI6MjA1OTAxMDAwNn0.g5Aub8R4CHxBjB-Xbh8v4dKqZ-aFVg2UASLLmMMmkug"